name: End-to-End DevOps CI/CD

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      SONAR_HOST_URL: http://50.19.42.141:9000
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Frontend Compilation
        run: |
          cd client
          find . -name "*.js" -exec node --check {} +

      - name: Backend Compilation
        run: |
          cd server
          find . -name "*.js" -exec node --check {} +

      - name: GitLeaks Scan
        run: |
          gitleaks detect --source ./client --exit-code 1 || true
          gitleaks detect --source ./server --exit-code 1 || true

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./client

      - name: Install backend dependencies
        run: npm install
        working-directory: ./server

      - name: SonarQube Scan Frontend
        run: |
          sonar-scanner \
            -Dsonar.projectKey=frontend-project \
            -Dsonar.sources=client \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      - name: SonarQube Scan Backend
        run: |
          sonar-scanner \
            -Dsonar.projectKey=backend-project \
            -Dsonar.sources=server \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      - name: Trivy FS Scan
        run: trivy fs --format table -o fs-report.html .

      - name: Build & Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: mokchhedul/branchbackend:latest
          load: false
          secrets: |
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Trivy Backend Image Scan
        run: trivy image --format table -o backend-image-report.html mokchhedul/branchbackend:latest

      - name: Build & Push Frontend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: mokchhedul/branchfrontend:latest
          load: false
          secrets: |
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Trivy Frontend Image Scan
        run: trivy image --format table -o frontend-image-report.html mokchhedul/branchfrontend:latest
